---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: final-udend-capstone
  region: us-east-1
  version: "1.19"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
    enableSsm: true

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:us-east-1:086206848953:key/6dfe5186-64bc-4fe2-8b09-2bfa6ed42a2b
