apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - image: bchanak/capstone:latest
        imagePullPolicy: Always
        name: capstone-container
        ports:
        - containerPort: 80
          protocol: TCP